#!/usr/bin/env python3
"""
Generate walkable path coordinates between CMU buildings using OpenRouteService.

Reads ORS_API_KEY from ../.env and building coordinates from ../data/buildings.json.
Prints a TypeScript snippet ready to paste into data/tourRoutes.ts.

Usage:
  python scripts/generate_tour_segment.py AN DH
  python scripts/generate_tour_segment.py AN DH BH CFA    # all consecutive pairs
"""

from __future__ import annotations

import json
import pathlib
import sys
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
BUILDINGS_JSON = ROOT / "data" / "buildings.json"
ENV_FILE = ROOT / ".env"
ORS_URL = "https://api.openrouteservice.org/v2/directions/foot-walking/geojson"


def load_env_key() -> str:
    if not ENV_FILE.exists():
        sys.exit(f"error: .env file not found at {ENV_FILE}")
    for raw in ENV_FILE.read_text().splitlines():
        line = raw.strip()
        if line.startswith("ORS_API_KEY="):
            return line.split("=", 1)[1].strip().strip('"').strip("'")
    sys.exit("error: ORS_API_KEY not set in .env")


def load_buildings() -> dict:
    return json.loads(BUILDINGS_JSON.read_text())


def fetch_route(api_key: str, start: tuple[float, float], end: tuple[float, float]) -> list[dict]:
    """Call ORS foot-walking; return list of {latitude, longitude} along the path."""
    body = json.dumps(
        # ORS expects [lng, lat] pairs
        {"coordinates": [[start[1], start[0]], [end[1], end[0]]]}
    ).encode("utf-8")
    req = urllib.request.Request(
        ORS_URL,
        data=body,
        headers={
            "Authorization": api_key,
            "Content-Type": "application/json",
            "Accept": "application/geo+json",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        sys.exit(f"ORS HTTP {e.code}: {e.read().decode('utf-8', errors='replace')}")
    except urllib.error.URLError as e:
        sys.exit(f"ORS network error: {e}")

    coords = data["features"][0]["geometry"]["coordinates"]
    return [{"latitude": c[1], "longitude": c[0]} for c in coords]


def format_segment(from_id: str, to_id: str, coords: list[dict]) -> str:
    lines = [f"  '{from_id}->{to_id}': {{"]
    lines.append(f"    from: '{from_id}',")
    lines.append(f"    to: '{to_id}',")
    lines.append("    coordinates: [")
    for c in coords:
        lines.append(
            f"      {{ latitude: {c['latitude']:.6f}, longitude: {c['longitude']:.6f} }},"
        )
    lines.append("    ],")
    lines.append("  },")
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) < 3:
        sys.exit("usage: python scripts/generate_tour_segment.py FROM_ID TO_ID [MORE_IDS...]")

    ids = sys.argv[1:]
    buildings = load_buildings()

    for bid in ids:
        if bid not in buildings:
            sys.exit(f"unknown building id: {bid}")
        b = buildings[bid]
        if not b.get("latitude") or not b.get("longitude"):
            sys.exit(f"building {bid} has no coordinates in buildings.json")

    api_key = load_env_key()

    print("// Generated by scripts/generate_tour_segment.py")
    print()
    for i in range(len(ids) - 1):
        a, b = ids[i], ids[i + 1]
        ba, bb = buildings[a], buildings[b]
        print(f"// {a} ({ba['title']}) -> {b} ({bb['title']})", file=sys.stderr)
        coords = fetch_route(
            api_key,
            (ba["latitude"], ba["longitude"]),
            (bb["latitude"], bb["longitude"]),
        )
        print(f"//   {len(coords)} waypoints", file=sys.stderr)
        print(format_segment(a, b, coords))
        print()


if __name__ == "__main__":
    main()
